spring:
  application:
    name: maplefusion-domain
  config:
    import:
      - classpath:config/application-mysql.yaml
      - classpath:config/application-logging.yaml
  profiles:
    group:
      default:
        - "local"
        - "local-mysql"
        - "local-logging"
      local:
        - "local"
        - "local-mysql"
        - "local-logging"